; Generated by AutoGUI 2.6.1
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

Gui Add, GroupBox, x16 y16 w96 h64, Country Code
Gui Add, Edit, x32 y40 w64 h21, 1
Gui Add, Text, x32 y64 w65 h14 +Disabled    , 1Required field
Gui Add, GroupBox, x120 y16 w200 h64, Phone Number
Gui Add, Edit, x136 y40 w168 h21, 2
Gui Add, Text, x136 y64 w168 h14 +Disabled    , 2Required field
Gui Add, GroupBox, x328 y16 w96 h64, Passenger No.
Gui Add, Edit, x344 y40 w64 h21, 3
Gui Add, Text, x344 y64 w65 h14 +Disabled    , 3Optional field
Gui Add, Button, x328 y96 w96 h31, Add

Gui Show, w440 h144, CTCM - Mobile Contact
Return

GuiEscape:
GuiClose:
    ExitApp
