; Generated by AutoGUI 2.6.1
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

Gui Add, GroupBox, x16 y16 w160 h152, Contact Commands
Gui Add, Button, x32 y40 w128 h31, Email
Gui Add, Button, x32 y80 w128 h31, Phone
Gui Add, Button, x32 y120 w128 h31, Reject
Gui Add, GroupBox, x184 y16 w160 h152, APIS Commands
Gui Add, Button, x200 y40 w128 h31, Passport
Gui Add, Button, x200 y80 w128 h31, Visa
Gui Add, Button, x200 y120 w128 h31, Destination

Gui Show, w360 h183, Quick Command List [Sabre GDS]
Return

GuiEscape:
GuiClose:
    ExitApp
