; Generated by AutoGUI 2.6.1
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

Gui Add, GroupBox, x16 y16 w304 h64    , Email address
Gui Add, Edit, x32 y40 w274 h21, 1
Gui Add, Text, x32 y64 w274 h14 +Disabled   , 1Required field
Gui Add, GroupBox, x16 y96 w200 h64    , SSR Arlines
Gui Add, DropDownList, x32 y120 w168    , Non AA (GFAX)||AA (FAX)
Gui Add, Text, x32 y144 w168 h14 +Disabled   , 2Required field
Gui Add, GroupBox, x224 y96 w96 h64    , Passenger No.
Gui Add, Edit, x240 y120 w64 h21, 3
Gui Add, Text, x240 y144 w65 h14 +Disabled   , 3Required field
Gui Add, Button, x224 y176 w96 h31, Add

Gui Show, x851 y371 w336 h224, CTCE - Email Contact
Return

GuiEscape:
GuiClose:
    ExitApp
